[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Dev Log"
  pageRef = "devlog"
  weight = 30

[[main]]
  name = "YouTube"
  pageRef = "youtube"
  weight = 40

[[main]]
  name = "About"
  pageRef = "about"
  weight = 50

[[footer]]
  name = "GitHub"
  url = "https://github.com/kjalba"
  weight = 10

[[footer]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/kjalba"
  weight = 20

[[footer]]
  name = "YouTube"
  url = "https://youtube.com/@kjalba"
  weight = 30
